//THIS FILE IS GENERATED BY MARFU, DO NOT EDIT IT!
using System;
using System.Text;
using System.Collections.Generic;
namespace Rof
{
public class RofLocalizationRow
{
public int ID { get; private set; }
public string Type { get; private set; }
public string English { get; private set; }
public string Chinese { get; private set; }
public int ReadBody(byte[] rData, int nOffset)
{
if (BitConverter.IsLittleEndian){Array.Reverse(rData, nOffset, 4);}
this.ID = BitConverter.ToInt32(rData, nOffset); nOffset += 4;
if (BitConverter.IsLittleEndian){Array.Reverse(rData, nOffset, 4);}
int nTypeLen = (int)BitConverter.ToUInt32(rData, nOffset); nOffset += 4;
this.Type = Encoding.UTF8.GetString(rData, nOffset, nTypeLen); nOffset += nTypeLen;
if (BitConverter.IsLittleEndian){Array.Reverse(rData, nOffset, 4);}
int nEnglishLen = (int)BitConverter.ToUInt32(rData, nOffset); nOffset += 4;
this.English = Encoding.UTF8.GetString(rData, nOffset, nEnglishLen); nOffset += nEnglishLen;
if (BitConverter.IsLittleEndian){Array.Reverse(rData, nOffset, 4);}
int nChineseLen = (int)BitConverter.ToUInt32(rData, nOffset); nOffset += 4;
this.Chinese = Encoding.UTF8.GetString(rData, nOffset, nChineseLen); nOffset += nChineseLen;
return nOffset;
}
}
public class RofLocalizationTable
{
private int mRowNum;
private Dictionary<int, RofLocalizationRow> mIDMap;
private Dictionary<int, int> mRowMap;
public int RowNum { get { return this.mRowNum; } }
public void Init(byte[] rTotalBuffer)
{
mIDMap = new Dictionary<int, RofLocalizationRow>();
this.mRowMap = new Dictionary<int, int>();
int nOffset = 0;
if (BitConverter.IsLittleEndian) { Array.Reverse(rTotalBuffer, nOffset, 4); }
this.mRowNum = BitConverter.ToInt32(rTotalBuffer, nOffset); nOffset += 4;
for (int i = 0; i < this.mRowNum; i++)
{
if (BitConverter.IsLittleEndian) { Array.Reverse(rTotalBuffer, nOffset, 4); }
int nID = BitConverter.ToInt32(rTotalBuffer, nOffset);
RofLocalizationRow rModel = new RofLocalizationRow();
if (BitConverter.IsLittleEndian) { Array.Reverse(rTotalBuffer, nOffset, 4); }
nOffset = rModel.ReadBody(rTotalBuffer, nOffset);
this.mIDMap.Add(nID, rModel);
this.mRowMap.Add(i, nID);
}
}
public RofLocalizationRow GetDataByID(int nID)
{
if (this.mIDMap.ContainsKey(nID) == false)
{
return null;
}
return this.mIDMap[nID];
}
public RofLocalizationRow GetDataByRow(int nIndex)
{
if (mRowMap.ContainsKey(nIndex) == false)
{
return null;
}
int nID = mRowMap[nIndex];
return mIDMap[nID];
}
}
}
